server:
  port: 80

ribbon:
  eureka:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:file:./data/data
    driverClassName: org.h2.Driver
    username: ptz
    password: ptz
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /api/h2/

zuul:
  routes:
    ptz:
      path: /ptz/**
      url: ""
    vmix:
      path: /vmix/**
      url: ""

secrets:
  youtube:
    client_id: ${PTZ_YOUTUBE_CLIENT_ID}
    client_secret: ${PTZ_YOUTUBE_CLIENT_SECRET}
  facebook:
    client_id: ${PTZ_FACEBOOK_CLIENT_ID}
    client_secret: ${PTZ_FACEBOOK_CLIENT_SECRET}

# logging:
#   level:
#     org.springframework.web: DEBUG
#     com.netflix.zuul: DEBUG
